
import React, { useState, useRef, useEffect } from 'react';
import JSZip from 'jszip';
import { generateCode } from './services/gemini';
import { AppState, CodeFile, ChatMessage } from './types';
import { CodeIcon, DatabaseIcon, DownloadIcon, MagicIcon, ZipIcon, SendIcon, TrashIcon, UserIcon, PlusIcon, CheckCircleIcon } from './components/Icons';

const App: React.FC = () => {
  const [promptInput, setPromptInput] = useState<string>('');
  const [state, setState] = useState<AppState>(AppState.IDLE);
  const [messages, setMessages] = useState<ChatMessage[]>([]);
  
  // Project State
  const [files, setFiles] = useState<CodeFile[]>([]);
  const [databaseInstructions, setDatabaseInstructions] = useState<string | null>(null);
  const [lastModifiedFiles, setLastModifiedFiles] = useState<string[]>([]);
  
  // UI State
  const [activeTab, setActiveTab] = useState<'code' | 'db'>('code');
  const [activeFileIndex, setActiveFileIndex] = useState<number>(0);
  const messagesEndRef = useRef<HTMLDivElement>(null);

  // Auto-scroll to bottom of chat
  useEffect(() => {
    messagesEndRef.current?.scrollIntoView({ behavior: 'smooth' });
  }, [messages, state]);

  const handleSend = async () => {
    if (!promptInput.trim()) return;

    const userMessage: ChatMessage = {
      role: 'user',
      content: promptInput,
      timestamp: Date.now()
    };

    setMessages(prev => [...prev, userMessage]);
    setPromptInput('');
    setState(AppState.GENERATING);

    try {
      const response = await generateCode(files, userMessage.content, messages);

      const aiMessage: ChatMessage = {
        role: 'model',
        content: response.message,
        timestamp: Date.now()
      };

      setMessages(prev => [...prev, aiMessage]);
      
      if (response.files && response.files.length > 0) {
        const modifiedNames = response.files.map(f => f.filename);
        setLastModifiedFiles(modifiedNames);

        setFiles(prevFiles => {
          const newFilesMap = new Map(prevFiles.map(f => [f.filename, f]));
          response.files.forEach(f => {
            newFilesMap.set(f.filename, f);
          });
          return Array.from(newFilesMap.values());
        });
        
        // If files were empty (new project), set active file to first one
        if (files.length === 0 && response.files.length > 0) {
          setActiveFileIndex(0);
        }
      }

      if (response.databaseInstructions) {
        setDatabaseInstructions(response.databaseInstructions);
      }

      setState(AppState.IDLE);
    } catch (err) {
      console.error(err);
      setState(AppState.ERROR);
      setMessages(prev => [...prev, {
        role: 'model',
        content: 'متاسفانه در ارتباط با هوش مصنوعی خطایی رخ داد. لطفا دوباره تلاش کنید.',
        timestamp: Date.now()
      }]);
    }
  };

  const deleteProject = () => {
    if (window.confirm('آیا مطمئن هستید؟ تمام کدها و تاریخچه چت حذف خواهد شد.')) {
      setMessages([]);
      setFiles([]);
      setDatabaseInstructions(null);
      setLastModifiedFiles([]);
      setPromptInput('');
      setState(AppState.IDLE);
    }
  };

  const startNewProject = () => {
    if (files.length > 0) {
      if (!window.confirm('پروژه فعلی بسته خواهد شد. آیا مطمئن هستید که می‌خواهید پروژه جدیدی شروع کنید؟')) {
        return;
      }
    }
    setMessages([]);
    setFiles([]);
    setDatabaseInstructions(null);
    setLastModifiedFiles([]);
    setPromptInput('');
    setState(AppState.IDLE);
    // Optional: Add a welcome message for the new project
  };

  const handleCodeChange = (newContent: string) => {
    if (files.length === 0) return;
    const updatedFiles = [...files];
    updatedFiles[activeFileIndex] = {
      ...updatedFiles[activeFileIndex],
      content: newContent
    };
    setFiles(updatedFiles);
  };

  const downloadFile = (file: CodeFile) => {
    const blob = new Blob([file.content], { type: 'text/plain' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = file.filename.split('/').pop() || file.filename; // Simple safety for paths
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);
  };

  const downloadAllZip = async () => {
    if (!files.length) return;
    const zip = new JSZip();
    files.forEach(file => zip.file(file.filename, file.content));
    if (databaseInstructions) {
      zip.file("DATABASE_INSTRUCTIONS.md", databaseInstructions);
    }
    
    // Create a README from the conversation context
    const lastAiMsg = [...messages].reverse().find(m => m.role === 'model');
    const readmeContent = `# CodeMaster Project\n\nGenerated by CodeMaster AI.\n\n## Latest Update\n${lastAiMsg?.content || "Initial generation"}`;
    zip.file("README_AI.md", readmeContent);

    try {
      const content = await zip.generateAsync({ type: "blob" });
      const url = URL.createObjectURL(content);
      const a = document.createElement('a');
      a.href = url;
      a.download = "codemaster_project.zip";
      document.body.appendChild(a);
      a.click();
      document.body.removeChild(a);
      URL.revokeObjectURL(url);
    } catch (err) {
      alert("خطا در ایجاد فایل زیپ");
    }
  };

  // Improved markdown-like rendering for chat
  const renderMessageContent = (text: string) => {
    // Very basic parsing for bold and code blocks
    return text.split('\n').map((line, i) => {
        // Simple detection of code blocks or lists (enhancement possible with proper markdown lib)
        if (line.startsWith('- ') || line.startsWith('* ')) {
            return <li key={i} className="ml-4 list-disc">{line.substring(2)}</li>
        }
        return <p key={i} className="mb-1 min-h-[1rem]">{line}</p>;
    });
  };

  return (
    <div className="min-h-screen bg-[#020617] text-slate-300 flex flex-col md:flex-row overflow-hidden font-sans selection:bg-indigo-500/30">
      
      {/* Sidebar / Chat Section */}
      <aside className="w-full md:w-[400px] bg-[#0f172a] border-l border-slate-800 flex flex-col h-[40vh] md:h-screen shadow-2xl z-20 shrink-0">
        
        {/* Header */}
        <div className="p-4 border-b border-slate-800 bg-[#0f172a] flex justify-between items-center shrink-0">
          <div className="flex items-center gap-2">
            <div className="w-8 h-8 rounded-lg bg-gradient-to-br from-indigo-500 to-purple-600 flex items-center justify-center shadow-lg shadow-indigo-500/20">
              <MagicIcon className="w-5 h-5 text-white" />
            </div>
            <div>
               <h1 className="font-bold text-slate-100 leading-tight">CodeMaster</h1>
               <p className="text-[10px] text-indigo-400 font-mono tracking-wider">PRO VERSION</p>
            </div>
          </div>
          
          <div className="flex items-center gap-1">
             <button onClick={startNewProject} className="p-2 text-slate-400 hover:text-white hover:bg-slate-800 rounded-lg transition-colors" title="پروژه جدید">
               <PlusIcon className="w-5 h-5" />
             </button>
             {files.length > 0 && (
                <button onClick={deleteProject} className="p-2 text-slate-400 hover:text-red-400 hover:bg-slate-800 rounded-lg transition-colors" title="حذف پروژه">
                  <TrashIcon className="w-5 h-5" />
                </button>
             )}
          </div>
        </div>

        {/* Messages Area */}
        <div className="flex-1 overflow-y-auto p-4 space-y-6 scroll-smooth">
          {messages.length === 0 ? (
            <div className="h-full flex flex-col items-center justify-center text-slate-500 text-center opacity-80 px-6">
              <div className="w-16 h-16 rounded-2xl bg-slate-800/50 flex items-center justify-center mb-4 ring-1 ring-slate-700">
                  <MagicIcon className="w-8 h-8 text-indigo-500" />
              </div>
              <h3 className="text-slate-200 font-bold mb-2">شروع پروژه جدید</h3>
              <p className="text-sm text-slate-400 leading-relaxed">
                ایده خود را بگویید تا کدها را برای شما بسازم. 
                <br />
                <span className="text-xs mt-2 block text-slate-500">مثلا: "یک سایت فروشگاهی با React و Nodejs بساز"</span>
              </p>
            </div>
          ) : (
            messages.map((msg, idx) => (
              <div key={idx} className={`flex gap-3 animate-in fade-in slide-in-from-bottom-2 duration-300 ${msg.role === 'user' ? 'flex-row-reverse' : 'flex-row'}`}>
                <div className={`w-8 h-8 rounded-full flex items-center justify-center shrink-0 border ${msg.role === 'user' ? 'bg-indigo-600 border-indigo-500 text-white' : 'bg-slate-700 border-slate-600 text-indigo-300'}`}>
                  {msg.role === 'user' ? <UserIcon className="w-5 h-5" /> : <MagicIcon className="w-5 h-5" />}
                </div>
                <div className={`max-w-[85%] rounded-2xl p-4 text-sm leading-6 shadow-sm ${
                    msg.role === 'user' 
                    ? 'bg-indigo-600 text-white rounded-tr-none' 
                    : 'bg-slate-800 border border-slate-700 text-slate-300 rounded-tl-none'
                  }`}>
                  {renderMessageContent(msg.content)}
                </div>
              </div>
            ))
          )}
          {state === AppState.GENERATING && (
            <div className="flex gap-3">
              <div className="w-8 h-8 rounded-full bg-slate-800 border border-slate-700 flex items-center justify-center shrink-0">
                 <div className="w-4 h-4 border-2 border-indigo-500 border-t-transparent rounded-full animate-spin"></div>
              </div>
              <div className="bg-slate-800 border border-slate-700 text-slate-400 rounded-2xl rounded-tl-none p-3 px-4 text-sm flex items-center gap-2">
                <span className="text-xs font-medium animate-pulse">در حال نوشتن کد...</span>
              </div>
            </div>
          )}
          <div ref={messagesEndRef} />
        </div>

        {/* Input Area */}
        <div className="p-4 border-t border-slate-800 bg-[#0f172a] shrink-0">
          <div className="relative group">
            <textarea
              value={promptInput}
              onChange={(e) => setPromptInput(e.target.value)}
              onKeyDown={(e) => {
                if (e.key === 'Enter' && !e.shiftKey) {
                  e.preventDefault();
                  handleSend();
                }
              }}
              placeholder="دستور خود را اینجا بنویسید..."
              className="w-full bg-slate-900 border border-slate-700 rounded-xl p-3 pr-4 pl-12 text-sm focus:ring-2 focus:ring-indigo-500/50 focus:border-indigo-500 outline-none resize-none h-14 max-h-32 placeholder-slate-500 transition-all text-right dir-rtl"
              disabled={state === AppState.GENERATING}
              dir="rtl"
            />
            <button
              onClick={handleSend}
              disabled={!promptInput.trim() || state === AppState.GENERATING}
              className="absolute left-2 bottom-2 p-2 bg-indigo-600 hover:bg-indigo-500 text-white rounded-lg transition-all disabled:opacity-50 disabled:cursor-not-allowed shadow-lg shadow-indigo-600/20"
            >
              <SendIcon className="w-4 h-4" />
            </button>
          </div>
        </div>
      </aside>

      {/* Main Content Area */}
      <main className="flex-1 flex flex-col h-[60vh] md:h-screen relative bg-[#020617]">
        {files.length === 0 ? (
          <div className="flex flex-col items-center justify-center h-full text-slate-600">
            <div className="w-24 h-24 rounded-full bg-slate-900 border border-slate-800 flex items-center justify-center mb-6 shadow-2xl">
               <CodeIcon className="w-10 h-10 opacity-40" />
            </div>
            <p className="text-xl font-medium opacity-60">فضای کاری خالی است</p>
            <p className="text-sm mt-2 opacity-40">برای شروع یک پروژه جدید با هوش مصنوعی گفتگو کنید</p>
          </div>
        ) : (
          <>
            {/* Toolbar */}
            <header className="h-14 bg-[#0f172a] border-b border-slate-800 flex items-center justify-between px-4 shrink-0">
              <div className="flex gap-1 bg-slate-900/50 p-1 rounded-lg border border-slate-800">
                <button
                  onClick={() => setActiveTab('code')}
                  className={`flex items-center gap-2 px-4 py-1.5 rounded-md text-xs font-medium transition-all ${
                    activeTab === 'code' 
                    ? 'bg-indigo-600 text-white shadow-md shadow-indigo-900/20' 
                    : 'text-slate-400 hover:text-slate-200 hover:bg-slate-800'
                  }`}
                >
                  <CodeIcon className="w-4 h-4" />
                  Editor
                </button>
                <button
                  onClick={() => setActiveTab('db')}
                  className={`flex items-center gap-2 px-4 py-1.5 rounded-md text-xs font-medium transition-all ${
                    activeTab === 'db' 
                    ? 'bg-indigo-600 text-white shadow-md shadow-indigo-900/20' 
                    : 'text-slate-400 hover:text-slate-200 hover:bg-slate-800'
                  }`}
                >
                  <DatabaseIcon className="w-4 h-4" />
                  Database
                  {databaseInstructions && <span className="w-1.5 h-1.5 bg-emerald-500 rounded-full ml-1 animate-pulse"></span>}
                </button>
              </div>

              <div className="flex gap-2">
                <button
                    onClick={downloadAllZip}
                    className="flex items-center gap-2 px-3 py-1.5 bg-slate-800 text-slate-300 border border-slate-700 hover:bg-slate-700 hover:text-white rounded-lg text-xs font-bold transition-all"
                    title="دانلود کل پروژه (ZIP)"
                  >
                    <ZipIcon className="w-4 h-4" />
                    <span className="hidden lg:inline">Download ZIP</span>
                  </button>
                <button
                  onClick={() => downloadFile(files[activeFileIndex])}
                  className="flex items-center gap-2 px-3 py-1.5 bg-slate-800 text-slate-300 border border-slate-700 hover:bg-slate-700 hover:text-white rounded-lg text-xs font-bold transition-all"
                  title="دانلود فایل فعلی"
                >
                  <DownloadIcon className="w-4 h-4" />
                  <span className="hidden lg:inline">File</span>
                </button>
              </div>
            </header>

            <div className="flex-1 flex overflow-hidden">
               {/* CODE TAB */}
               {activeTab === 'code' && (
                 <>
                   {/* File Explorer */}
                   <div className="w-56 md:w-64 bg-[#0f172a] border-l border-slate-800 flex flex-col shrink-0">
                      <div className="p-3 px-4 text-[10px] font-bold text-slate-500 uppercase tracking-wider flex items-center justify-between">
                        <span>Explorer</span>
                        <span className="bg-slate-800 px-1.5 rounded text-slate-400">{files.length}</span>
                      </div>
                      <div className="overflow-y-auto flex-1 p-2 space-y-0.5">
                        {files.map((file, idx) => {
                          const isModified = lastModifiedFiles.includes(file.filename);
                          return (
                            <button
                              key={idx}
                              onClick={() => setActiveFileIndex(idx)}
                              className={`w-full text-left px-3 py-2 rounded-md text-xs truncate transition-all flex justify-between items-center group relative
                                ${activeFileIndex === idx 
                                  ? 'bg-indigo-500/10 text-indigo-400 border border-indigo-500/20' 
                                  : 'text-slate-400 hover:bg-slate-800 hover:text-slate-200 border border-transparent'
                                }`}
                              dir="ltr"
                            >
                              <div className="flex items-center gap-2 truncate">
                                {/* Simple icon based on extension could go here */}
                                <span className="font-mono">{file.filename}</span>
                              </div>
                              {isModified && (
                                 <span className="flex h-2 w-2 relative">
                                   <span className="animate-ping absolute inline-flex h-full w-full rounded-full bg-emerald-400 opacity-75"></span>
                                   <span className="relative inline-flex rounded-full h-2 w-2 bg-emerald-500"></span>
                                 </span>
                              )}
                            </button>
                          );
                        })}
                      </div>
                   </div>

                   {/* Editor Area */}
                   <div className="flex-1 flex flex-col bg-[#020617] relative overflow-hidden">
                      {/* Breadcrumb / File Info */}
                      <div className="h-8 bg-[#020617] border-b border-slate-800 flex items-center px-4 justify-between select-none">
                         <span className="text-xs text-slate-500 font-mono">{files[activeFileIndex].filename}</span>
                         <span className="text-[10px] text-slate-600 font-mono uppercase px-2 py-0.5 rounded bg-slate-900 border border-slate-800">
                           {files[activeFileIndex].language}
                         </span>
                      </div>
                      
                      <div className="flex-1 relative">
                        <textarea
                          value={files[activeFileIndex].content}
                          onChange={(e) => handleCodeChange(e.target.value)}
                          className="w-full h-full bg-[#020617] text-slate-300 font-mono text-sm p-4 outline-none resize-none leading-relaxed selection:bg-indigo-900"
                          spellCheck={false}
                          dir="ltr"
                        />
                      </div>
                   </div>
                 </>
               )}

               {/* DATABASE TAB */}
               {activeTab === 'db' && (
                  <div className="flex-1 overflow-y-auto p-8 bg-[#020617]">
                    <div className="max-w-4xl mx-auto">
                      {databaseInstructions ? (
                        <div className="bg-[#0f172a] rounded-xl border border-slate-800 shadow-2xl overflow-hidden">
                          <div className="bg-slate-900/50 p-4 border-b border-slate-800 flex items-center gap-3">
                             <div className="p-2 bg-emerald-500/10 rounded-lg text-emerald-500">
                               <DatabaseIcon className="w-5 h-5" />
                             </div>
                             <h3 className="text-lg font-bold text-slate-200">Database Configuration</h3>
                          </div>
                          <div className="p-6">
                            <pre className="font-mono text-sm text-slate-300 whitespace-pre-wrap leading-7 bg-black/20 p-4 rounded-lg border border-slate-800/50">
                              {databaseInstructions}
                            </pre>
                          </div>
                        </div>
                      ) : (
                        <div className="text-center p-16 rounded-2xl border border-dashed border-slate-800 opacity-50">
                           <DatabaseIcon className="w-16 h-16 mx-auto mb-4 text-slate-700" />
                          <p className="text-slate-500 text-lg">No database configuration required for this project.</p>
                        </div>
                      )}
                    </div>
                  </div>
               )}
            </div>
          </>
        )}
      </main>
    </div>
  );
};

export default App;
